-- Tabla de Normativas
CREATE TABLE IF NOT EXISTS normativas (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    entidad TEXT,
    norma_legal TEXT,
    descripcion TEXT,
    fecha_publicacion DATE,
    link_acceso TEXT,
    tipo_norma TEXT,
    area_tematica TEXT,
    categoria TEXT,
    categoria_antiguedad TEXT,
    fecha_registro TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para búsqueda rápida en Normativas
CREATE INDEX IF NOT EXISTS idx_normativas_entidad ON normativas(entidad);
CREATE INDEX IF NOT EXISTS idx_normativas_categoria ON normativas(categoria);
CREATE INDEX IF NOT EXISTS idx_normativas_fecha ON normativas(fecha_publicacion);

-- Tabla de Convocatorias
CREATE TABLE IF NOT EXISTS convocatorias (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fuente TEXT,
    organizacion TEXT,
    cargo TEXT,
    remuneracion_numerica NUMERIC,
    categoria_salarial TEXT,
    ubicacion TEXT,
    fecha_fin DATE,
    link TEXT,
    es_nueva BOOLEAN DEFAULT FALSE,
    categoria_busqueda TEXT,
    fecha_registro TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para Convocatorias
CREATE INDEX IF NOT EXISTS idx_convocatorias_organizacion ON convocatorias(organizacion);
CREATE INDEX IF NOT EXISTS idx_convocatorias_ubicacion ON convocatorias(ubicacion);
CREATE INDEX IF NOT EXISTS idx_convocatorias_remuneracion ON convocatorias(remuneracion_numerica);
